# Generated by Django 3.2.8 on 2023-05-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Competence',
                'verbose_name_plural': 'Competences',
                'db_table': '"Competence"',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('CNI_resp', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=200)),
                ('Telephone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('CNI', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=200)),
                ('Prenom', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=200)),
                ('Telephone', models.CharField(max_length=200)),
                ('competence', models.ManyToManyField(related_name='skils', to='api.Competences')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Login', models.CharField(default='blanche', max_length=100)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': '"Utilisateur"',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=200)),
                ('CNI_resp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Postuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expert')),
                ('Num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projet')),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilisateur'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilisateur'),
        ),
    ]
