# Generated by Django 3.2.8 on 2023-05-22 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20230522_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mode',
        ),
        migrations.CreateModel(
            name='ProfileEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/photos_profiles/')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
