# Generated by Django 3.2.8 on 2023-05-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_profile_competences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='competences',
            field=models.ManyToManyField(related_name='competences', to='api.Competence'),
        ),
    ]
