# Generated by Django 3.2.8 on 2023-05-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230522_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=True, null=True, upload_to='photos_profiles/'),
        ),
        migrations.AlterField(
            model_name='profileentreprise',
            name='image',
            field=models.ImageField(default=True, upload_to='media/'),
        ),
    ]
