# Generated by Django 3.2.8 on 2023-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230522_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=True, null=True, upload_to='media/'),
        ),
    ]
