# Generated by Django 3.2.8 on 2023-05-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_project_travailleurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fini',
            field=models.CharField(choices=[('fini', 'fini'), ('non fini', 'non fini')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
