# Generated by Django 3.2.8 on 2023-05-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_project_travailleurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fini',
            field=models.CharField(choices=[('fini', 'fini'), ('non fini', 'non fini')], default=True, max_length=255),
        ),
    ]
