# Generated by Django 3.2.8 on 2023-05-22 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_project_fini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='devise',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='devise', to='api.unitedevise'),
        ),
    ]
