# Generated by Django 3.2.8 on 2023-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_project_travailleurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='competences', to='api.Competence'),
        ),
    ]
