# Generated by Django 3.2.8 on 2023-05-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_profile_competences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='titre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
